language: cpp

compiler:
  - gcc
  - clang

sudo: false

addons:
  apt:
    packages:
      - &default_packages [mysql-server]

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9-multilib

script:
  - g++ -v
  - clang++ -v

notifications:
  email: false

matrix:
  fast_finish: true
