language: cpp

compiler:
  - gcc
  - clang

sudo: false

addons:
  apt:
    packages:
      - &default_packages [mysql-server]

script:
  - g++ -v
  - clang++ -v

notifications:
  email: false

matrix:
  fast_finish: true
