language: cpp

sudo: false

cache: apt

_packages:
  - &default_packages
    - mysql-server
  - &GCC
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - *default_packages
          - g++-4.9-multilib
    before_install:
      - export CC="gcc-4.9"
      - export CXX="g++-4.9"
  - &Clang
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.6
        packages:
          - *default_packages
          - clang-3.6
    before_install:
      - export CC="clang-3.6"
      - export CXX="clang++-3.6"

matrix:
  include:
    # GCC
    - compiler: gcc
      <<: *GCC
      env:
    - compiler: gcc
      <<: *GCC
      env: DEBUG=1
    - compiler: gcc
      <<: *GCC
      env: DEBUG=2
    # Clang
    - compiler: clang
      <<: *Clang
      env:
    - compiler: clang
      <<: *Clang
      env: DEBUG=1
    - compiler: clang
      <<: *Clang
      env: DEBUG=2

script:
  - $CC --version
  - $CXX --version

notifications:
  email: false
