language: cpp

compiler:
  - gcc
  - clang

env:
  - AAA=1
  - AAA=2

sudo: false

addons:
  apt:
    packages:
      - &default_packages [mysql-server]

matrix:
  include:
    - env: AAA=1
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9-multilib

script:
  - g++ -v
  - clang++ -v

notifications:
  email: false

matrix:
  fast_finish: true
