language: cpp

sudo: false

cache: apt

notifications:
  email: false

_packages:
  - &default_packages
    - [zip, unzip]
  - &GCC
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - *default_packages
          - g++-4.9-multilib
    before_install:
      - export CC="gcc-4.9"
      - export CXX="g++-4.9"
  - &Clang
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.6
        packages:
          - *default_packages
          - clang-3.6
    before_install:
      - export CC="clang-3.6"
      - export CXX="clang++-3.6"

matrix:
  fast_finish: true
  include:
    # GCC
    - compiler: gcc
      <<: *GCC
      env:
    - compiler: gcc
      <<: *GCC
      env: DEBUG=1
    - compiler: gcc
      <<: *GCC
      env: DEBUG=2
    # Clang
    - compiler: clang
      <<: *Clang
      env:
    - compiler: clang
      <<: *Clang
      env: DEBUG=1
    - compiler: clang
      <<: *Clang
      env: DEBUG=2
  # Due to LLVM APT outage
  allow_failures:
    - compiler: clang

script:
  - $CC --version
  - $CXX --version
  - find /usr/include/ | grep unistd
  - ls -l /usr/include
  - wget 'http://de.archive.ubuntu.com/ubuntu/pool/main/libs/libseccomp/libseccomp-dev_2.3.1-2.1ubuntu4_amd64.deb'
  - dpkg --fsys-tarfile $(ls | grep libseccomp) | tar x --one-top-level=libseccomp
