language: cpp

sudo: false

cache: apt

addons:
  apt:
    packages: &default_packages
      - mysql-server

matrix:
  include:
    # GCC 4.9
    - compiler: gcc
      &GCC
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *default_packages
            - g++-4.9-multilib
    # Clang 3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - *default_packages
            - clang-3.6
    - compiler: gcc
      env: DEBUG=1
      *GCC

install:
  # Compiler
  - if [ "$CC" = "gcc" ]; then export CC="gcc-4.9"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi
  - if [ "$CC" = "clang" ]; then export CC="clang-3.6"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6"; fi

script:
  - $CC --version
  - $CXX --version

notifications:
  email: false
